### PR TITLE
Person and Local Resource validate phone

### LINKED ISSUE #167: Validate Phone when creating Person
- [ ] Client Side
- [ ] Server Side

### For client side
Utilize [inputmask](https://github.com/RobinHerbots/jquery.inputmask) for the phone field in the Create/Edit person form.

See [local_resources_form.js](https://github.com/matthew6project/thirtyone/blob/master/app/assets/javascripts/app.local_resources.js) for an example.

### For server side
Update the validations in the Person model. Look up how to use "validates_format_of" for help starting.
(You could use validates_numericality_of in conjunction with validates_length_of. Your choice.)

### PR DESCRIPTION
**Pull request by tasmar**
closes #167

### CODE REVIEW

**Comment by tasmar** [comment]
Note to self, I will need to update some tests before this can be merged

**Comment by jjulien** [comment]
Hey,
Did some looking into why your tests failed.  We're using this https://github.com/stympy/faker#fakerphonenumber in our people factory
https://github.com/tasmar/thirtyone/blob/person_validate_phone/spec/factories/people.rb#L19.  This randomly generates phone numbers in random formats.  

I do think we want to force everyone to enter their phone numbers the same, to one fix would be to change the faker to `phone     { Faker::Base.numerify("(###) ###-###-####") }
`.

One thing that did cross my mind as I read the docs was we're not supporting extensions in anyway.  Do you think we should have an optional `x####` option?

**Comment by Clete2** [comment]
Yes I think we should support extensions. At this time we aren't internationalizing it, but at least we should support all valid US combinations.

Clete Blackwell II

**Comment by tasmar** [comment]
I got the tests working for the regular phone numbers, but I still need to add the extensions so please no one merge this pull request yet.

**Pull request closed without merging**
