### PR TITLE
Fixes #150 Namespace javascript files.

### LINKED ISSUE #150: Organize javascript to allow better loading of page specific scripts.

### PR DESCRIPTION
**Pull request by davidleach**

### CODE REVIEW

**Comment by Clete2** [comment]
I'm struggling to understand the namespace again. You explained it well the other day but I'm a bit lost when looking at it.

Let's take app.local_resources, since I originally wrote that JS.

```
App.Local_Resources = {};

$(document).ready(function() {
  if (!($("body.local_resources").length > 0)) {
    return;
  }
...
```

Here, we aren't doing anything in ```App.Local_Resources```. Why initialize it?
I understand the ```if``` statement in the ```ready``` function, but I guess I thought it was supposed to go into ```App.Local_Resources``` somewhere and get executed.

**Comment by davidleach** [comment]
You're right to question the initialization.  If there's no javascript necessary for local resources then it isn't needed at all.  I just put it there as a boilerplate so that anyone who might come along later and want to add something would see how to get started.  We probably have plenty of examples in household though. 

Putting something in App.Local_Resources, such as

`App.Local_Resources.myAwesomeFunction = function() { alert('hi'); };`

is just a way to namespace your functions so there aren't any conflicts and other devs know where and what it's used for.  

Anything that you want **automatically executed on page load** AND that really **only needs to be executed in one of the views loaded through the local resources controller** would go into this document.ready section.  It checks the body tag for the class .local_resources, which is added on page load (it's just the name of the controller that loaded the page).

If you want to get really specific and only execute js on when the 'new' view of the local resources controller is rendered then you could make the check in document.ready something like:

`if (!($("body.local_resources.new").length > 0)) { }`

Does that help?

**Comment by davidleach** [comment]
For those reading this in the future, I totally stole this idea from Brandon Hilkert and his post http://brandonhilkert.com/blog/organizing-javascript-in-rails-application-with-turbolinks/

:smiley:

**Comment by Clete2** [comment]
Yes, thanks. Makes sense to me. I'll go ahead and merge it so we can all update on Monday night.

**Pull request merged**
